export default new Map<string, string>([
  ["display_name", "Name"],
  ["finish_position", "Finish"],
  ["finish_position_in_class", "Finish (In Class)"],
  ["laps_lead", "Laps Lead"],
  ["laps_complete", "Laps Completed"],
  ["interval", "Interval to P1"],
  ["class_interval", "Interval to P1 (In Class)"],
  ["average_lap", "AVG Laptime"],
  ["best_lap_num", "Fastest Lap"],
  ["best_lap_time", "Fastest Lap Time"],
  ["reason_out", "Status"],
  ["champ_points", "Points"],
  ["drop_race", "Drop Race"],
  ["club_points", "Club Points"],
  ["starting_position", "Starting Position"],
  ["starting_position_in_class", "Starting Position (In Class)"],
  ["car_class_short_name", "Car Class"],
  ["club_shortname", "Club"],
  ["division_name", "Division"],
  ["old_license_level", "Old License Level"],
  ["old_cpi", "Old Corners Per Incident"],
  ["oldi_rating", "Old iRating"],
  ["new_license_level", "New License Level"],
  ["new_cpi", "New Corners Per Incident"],
  ["newi_rating", "New iRating"],
  ["incidents", "Incidents"],
  ["car_name", "Car"],
  ["aggregate_champ_points", "Best Points For Week"],
  ["license_category", "License Category"],
  ["year", "Year"],
  ["season_number_of_year", "Season Number"],
  ["car_class_id", "Car Class ID"],
  ["division", "Division"],
  ["division_rank", "Rank (Division)"],
  ["overall_rank", "Rank (Overall)"],
  ["season_id", "Season ID"],
  ["season_name", "Season Name"],
  ["season_summary", "Season Summary"],
  ["weeks_counted", "Participation Weeks"],
  ["starts", "Starts"],
  ["wins", "Wins"],
  ["top5", "Top 5's"],
  ["top25_percent", "Top 25% Finishes"],
  ["poles", "Poles"],
  ["avg_start_position", "Average Starting Position"],
  ["avg_finish_position", "Average Finish Position"],
  ["avg_field_size", "Average Field Size"],
  ["laps", "Laps Completed"],
  ["laps_led", "Laps Led"],
  ["points", "Points"],
  ["category", "License Category"],
  ["safety_rating", "Safety Rating"],
  ["irating", "iRating"],
  ["group_name", "License Group Name"],
  ["race_week_num", "Race Week Number"],
  ["num_lead_changes", "Number of Lead Changes"],
  ["num_cautions", "Number of Cautions"],
  ["num_caution_laps", "Number of Caution Laps"],
  ["event_strength_of_field", "Strength of Field"],
  ["event_laps_complete", "Total Laps"],
  ["event_average_lap", "Average Lap Time"],
]);
