export default new Map<string,string>(
  [
    ["display_name", "Name"],
    ["finish_position", "Finish"],
    ["finish_position_in_class", "Finish (In Class)"],
    ['laps_lead', 'Laps Lead'],
    ["laps_complete", "Laps Completed"],
    ["interval", "Interval to P1"],
    ["class_interval", "Interval to P1 (In Class)"],
    ["average_lap", "AVG Laptime"],
    ["best_lap_num", "Fastest Lap"],
    ["best_lap_time", "Fastest Lap Time"],
    ["reason_out", "Status"],
    ["champ_points", "Points"],
    ["drop_race", "Drop Race"],
    ["club_points", "Club Points"],
    ["starting_position", "Starting Position"],
    ["starting_position_in_class", "Starting Position (In Class)"],
    ["car_class_short_name", "Car Class"],
    ["club_shortname", "Club"],
    ["division_name", "Division"],
    ["old_license_level", "Old License Level"],
    ["old_cpi", "Old Corners Per Incident"],
    ["oldi_rating", "Old iRating"],
    ["new_license_level", "New License Level"],
    ["new_cpi", "New Corners Per Incident"],
    ["newi_rating", "New iRating"],
    ["incidents", "Incidents"],
    ["car_name", "Car"],
    ["aggregate_champ_points", "Best Points For Week"],
  ]
)
