export default new Set([
  "cust_id",
  "display_name",
  "finish_position",
  "finish_position_in_class",
  "laps_complete",
  "interval",
  "class_interval",
  "average_lap",
  "best_lap_num",
  "best_lap_time",
  "car_class_short_name",
  "division_name",
  "incidents",
  "car_name",
]);
